"""initial

Revision ID: 5adec627ec95
Revises: 
Create Date: 2025-12-30 12:21:31.425319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5adec627ec95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # DROP OLD FIRST to avoid index name collision
    op.drop_index(op.f('idx_customer_hotel'), table_name='customerscomments')
    op.drop_table('customerscomments')
    
    op.create_table('customers_comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index('idx_customer_hotel', 'customers_comments', ['customer_id', 'hotel_id'], unique=False)
    
    # Cleaned up Identity column alterations
    op.add_column('bookings', sa.Column('num_guests', sa.Integer(), nullable=False))
    
    op.alter_column('bookings', 'expected_check_out_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_foreign_key(None, 'bookings', 'hotels', ['hotel_id'], ['hotel_id'])
    
    op.alter_column('customerfeedbacks', 'rating',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('customerfeedbacks', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_foreign_key(None, 'customerfeedbacks', 'hotels', ['hotel_id'], ['hotel_id'])
    
    op.drop_constraint(op.f('customers_gov_id_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_gov_id'), 'customers', ['gov_id'], unique=True)
    
    # RENAME column instead of Drop/Add to save data
    # Quoting "TermsCondtitons" because of mixed case
    op.execute('ALTER TABLE hotels RENAME COLUMN termscondtitons TO "TermsCondtitons"')
    
    op.drop_constraint(op.f('hotelusers_username_key'), 'hotelusers', type_='unique')
    op.create_index(op.f('ix_hotelusers_username'), 'hotelusers', ['username'], unique=True)
    op.create_foreign_key(None, 'hotelusers', 'hotels', ['hotel_id'], ['hotel_id'])
    
    op.alter_column('rooms', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['hotel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.alter_column('rooms', 'rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('rooms', 'room_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'hotelusers', type_='foreignkey')
    op.drop_index(op.f('ix_hotelusers_username'), table_name='hotelusers')
    op.create_unique_constraint(op.f('hotelusers_username_key'), 'hotelusers', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('hotelusers', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('hotels', sa.Column('termscondtitons', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('hotels', 'hotel_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('hotels', 'TermsCondtitons')
    op.drop_index(op.f('ix_customers_gov_id'), table_name='customers')
    op.create_unique_constraint(op.f('customers_gov_id_key'), 'customers', ['gov_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'customer_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'customerfeedbacks', type_='foreignkey')
    op.alter_column('customerfeedbacks', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customerfeedbacks', 'rating',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('customerfeedbacks', 'feedback_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.alter_column('bookings', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('bookings', 'expected_check_out_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('bookings', 'booking_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('bookings', 'num_guests')
    op.create_table('customerscomments',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('customers_comments_customer_id_fkey')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('customers_comments_pkey'))
    )
    op.create_index(op.f('idx_customer_hotel'), 'customerscomments', ['customer_id', 'hotel_id'], unique=False)
    op.drop_index('idx_customer_hotel', table_name='customers_comments')
    op.drop_table('customers_comments')
    # ### end Alembic commands ###
