"""refactor_naming

Revision ID: bcc1e31d8240
Revises: 5adec627ec95
Create Date: 2025-12-30 12:36:50.626511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc1e31d8240'
down_revision: Union[str, None] = '5adec627ec95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename Table
    op.rename_table('customers_comments', 'customer_notes')
    
    # Rename Column in that table (comment -> note)
    op.alter_column('customer_notes', 'comment', new_column_name='note')
    
    # Rename Column in Hotels (TermsCondtitons -> terms_and_conditions)
    # Quoting "TermsCondtitons" because of mixed case in DB
    op.execute('ALTER TABLE hotels RENAME COLUMN "TermsCondtitons" TO terms_and_conditions')
    
    # Re-create Index with new name if needed, or just let it exist.
    # The existing index was idx_customer_hotel. It is on the table.
    # Postgres keeps the index on rename.
    # Autogen tried to drop/create index. We can skip that if we renamed.
    # Valid Renames complete. No identity column alterations here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'room_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hotelusers', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('hotels', sa.Column('TermsCondtitons', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('hotels', 'hotel_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('hotels', 'terms_and_conditions')
    op.alter_column('customers', 'customer_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customerfeedbacks', 'feedback_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('bookings', 'booking_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('customers_comments',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('customers_comments_customer_id_fkey')),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.hotel_id'], name=op.f('customers_comments_hotel_id_fkey')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('customers_comments_pkey'))
    )
    op.create_index(op.f('idx_customer_hotel'), 'customers_comments', ['customer_id', 'hotel_id'], unique=False)
    op.drop_index('idx_customer_hotel', table_name='customer_notes')
    op.drop_table('customer_notes')
    # ### end Alembic commands ###
